<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Project;
use Illuminate\Database\Seeder;

class AnhSinhDataSeeder extends Seeder
{
    public function run(): void
    {
        $client = Client::create([
            'name' => 'Anh Sinh',
            'email' => 'sinh.bestchoice@gmail.com',
            'company' => 'WebHieuQua',
            'notes' => 'Dữ liệu import từ Google Spreadsheet',
        ]);

        $projects = [
            [
                'name' => 'Thạch Cao Tiến Phát',
                'domain_name' => 'thachcaotienphat.com',
                'production_link' => 'https://thachcaotienphat.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_provider' => 'maychu.cloud',
                'hosting_details' => 'https://utrecht.maychu.cloud:2083/',
                'hosting_package' => '5GB',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Nội Thất Ô Tô Anh Tài',
                'domain_name' => 'noithatotoanhtai.com',
                'production_link' => 'https://noithatotoanhtai.com/',
                'design_link' => 'https://huynhbaauto.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_provider' => 'pavietnam.vn',
                'hosting_package' => '3GB',
            ],
            [
                'name' => 'Máy Chế Biến Gỗ Bình Dương',
                'domain_name' => 'maychebiengobinhduong.com',
                'production_link' => 'https://maychebiengobinhduong.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'ssl_provider' => 'Có SSL trả phí',
                'hosting_package' => '8GB',
                'domain_provider' => 'nina.vn',
            ],
            [
                'name' => 'Hoa Tươi Vĩnh Cửu',
                'domain_name' => 'hoatuoivinhcuu.com',
                'production_link' => 'https://hoatuoivinhcuu.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_provider' => 'pavietnam.vn',
                'hosting_package' => '5GB',
            ],
            [
                'name' => 'Gỗ Triều Hoàng Gia',
                'domain_name' => 'gotrieuhoanggia.com',
                'production_link' => 'https://gotrieuhoanggia.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'nina.vn',
            ],
            [
                'name' => 'Nhôm Kính Tuấn Kiệt',
                'domain_name' => 'nhomkinhtuankiet.com',
                'production_link' => 'https://nhomkinhtuankiet.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_provider' => 'maychu.cloud',
                'hosting_details' => 'IP: 103.77.162.40, https://varna.maychu.cloud:2083/',
                'hosting_package' => '3GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'PCCC Bình Phước (v1)',
                'domain_name' => 'pcccbinhphuoc.com.vn',
                'production_link' => 'https://pcccbinhphuoc.com.vn/',
                'demo_link' => 'https://webhieuqua.com/demo/pcccbinhphuoc/',
                'design_link' => 'https://pcccdongnai.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 550000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Tư Vấn Xây Dựng Bình Phước',
                'domain_name' => 'tuvanxaydungcongnghiep.com',
                'production_link' => 'https://tuvanxaydungbinhphuoc.com/',
                'demo_link' => 'https://webhieuqua.com/demo/tuvanxaydungbinhphuoc/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 550000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '2GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Tai Ruby Spa',
                'domain_name' => 'tairubyspa.com',
                'production_link' => 'https://tairubyspa.com/',
                'demo_link' => 'https://webhieuqua.com/demo/tairubyspa/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '2GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Ẩm Thực Hoa Phú',
                'domain_name' => 'amthuchoaphubinhduong.com',
                'production_link' => 'https://amthuchoaphu.com/',
                'demo_link' => 'https://webhieuqua.com/demo/amthuchoaphu/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '2GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Bảo Vệ Bình Phước',
                'domain_name' => 'baovebinhphuoc.com',
                'production_link' => 'http://baovebinhphuoc.com/',
                'demo_link' => 'https://webhieuqua.com/demo/baovebinhphuoc/bestweb/index.php',
                'features' => ['Cơ bản', 'Responsive', 'Mobile', 'Đa ngôn ngữ'],
                'project_price' => 1300000,
                'deposit_amount' => 650000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
            ],
            [
                'name' => 'Xe Ngọc Tuyết',
                'domain_name' => 'xengoctuyet.com',
                'production_link' => 'https://xengoctuyet.com/',
                'demo_link' => 'https://webhieuqua.com/demo/xengoctuyet/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'PCCC Bình Phước (v2)',
                'domain_name' => 'pcccdongnai.vn',
                'production_link' => 'https://pcccbinhphuoc.com/',
                'demo_link' => 'https://webhieuqua.com/demo/pcccbinhphuoc2/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '5GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Thủy Long Thành',
                'domain_name' => 'thuylongthanh.com',
                'production_link' => 'http://thuylongthanh.com/',
                'demo_link' => 'https://webhieuqua.com/demo/thuylongthanh/',
                'design_link' => 'https://thuytruongphat.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Mèo Nam Vĩnh Hòa',
                'domain_name' => 'meonamvinhhoa.com',
                'production_link' => 'https://meonamvinhhoa.com/',
                'demo_link' => 'https://webhieuqua.com/demo/meonamvinhhoa/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Cửa Cuốn Thanh Vũ',
                'domain_name' => 'cuacuoncuakeohaitoan.com',
                'production_link' => 'https://cuacuonthanhvu.com/',
                'demo_link' => 'https://webhieuqua.com/demo/cuacuonthanhvu/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Cơ Khí Nhật Phương Nam',
                'domain_name' => 'cokhinhatphuongnam.com',
                'production_link' => 'https://cokhinhathai.com/',
                'demo_link' => 'https://webhieuqua.com/demo/cokhi',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'pavietnam.vn',
                'description' => 'Giới thiệu, dịch vụ, tin tức, chính sách, sản phẩm có cấp 1, header có slogan chạy chữ + email + MXH, nút gọi 2 SĐT + zalo + map + fb + messenger',
            ],
            [
                'name' => 'Xe Nâng Trung Hiếu Bình Dương',
                'domain_name' => 'xenangtrunghieubinhduong.com',
                'production_link' => 'https://xenangtrunghieubinhduong.com/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '5GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'pavietnam.vn',
                'description' => 'Giới thiệu, dịch vụ, sản phẩm 1 cấp, album ảnh, tin tức, video, footer tự nhập, map dạng chi nhánh, nút gọi 2 số + zalo + messenger',
            ],
            [
                'name' => 'Thuê Xe Tự Lái Bàu Bàng',
                'domain_name' => 'thuexetulaibaubang.com',
                'production_link' => 'https://thuexetulaibaubang.com/',
                'demo_link' => 'https://webhieuqua.com/demo/thuexetulaibaubang/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'project_type' => 'upload_source',
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
                'hosting_details' => 'IP: 45.117.169.153',
            ],
            [
                'name' => 'VLXD Minh Anh',
                'domain_name' => 'vlxdminhanh.com',
                'production_link' => 'https://vlxdminhanh.com/',
                'demo_link' => 'https://webhieuqua.com/demo/vlxdminhanh/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'project_type' => 'upload_source',
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '5GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'blueweb.com.vn',
                'hosting_details' => 'IP: 103.7.41.224',
            ],
            [
                'name' => 'Ô Tô Sơn Đường Đức Hòa',
                'domain_name' => 'otosonduongduchoa.com',
                'production_link' => 'https://otosonduongduchoa.com/',
                'demo_link' => 'https://webhieuqua.com/demo/otosonduongduchoa/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Heo Rừng Miền Tây',
                'domain_name' => 'traigionghonghuetg.com',
                'production_link' => 'https://heorungmientay.vn/',
                'demo_link' => 'https://webhieuqua.com/demo/heorungmientay/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '2GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
                'hosting_details' => 'IP: 103.7.41.224, tên miền phụ: heorungmientay.vn',
                'description' => 'Tên miền chính: traigionghonghuetg.com, tên miền phụ: heorungmientay.vn',
            ],
            [
                'name' => 'Yến Sào Song Kim',
                'domain_name' => 'yensaosongkim.com',
                'production_link' => 'https://yensaosongkim.com/',
                'demo_link' => 'https://webhieuqua.com/demo/yensaosongkim/',
                'features' => ['Cơ bản', 'Responsive', 'Giỏ hàng'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '5GB',
                'ssl_provider' => 'Có SSL trả phí',
                'hosting_provider' => 'matbao.net',
            ],
            [
                'name' => 'Cửa Đồng Xoài',
                'domain_name' => 'cuadongxoai.com',
                'production_link' => 'https://cuadongxoai.com/',
                'demo_link' => 'https://webhieuqua.com/demo/cuadongxoai/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'project_type' => 'upload_source',
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Kỳ Quang Hải Sản',
                'domain_name' => 'kyquanghaisan.vn',
                'production_link' => 'https://kyquanghaisan.vn/',
                'demo_link' => 'https://webhieuqua.com/demo/kyquanghaisan/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'project_type' => 'upload_source',
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Davi Bakery',
                'domain_name' => 'bonglantrungmuoivungtau.com',
                'production_link' => 'https://davibakery.com/',
                'demo_link' => 'https://demo.webhieuqua.com/davibakery-c6NMQXdF/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '10GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Thanh Trung Fruits',
                'domain_name' => 'thanhtrungfruits.com',
                'production_link' => 'https://thanhtrungfruits.com/',
                'demo_link' => 'https://demo.webhieuqua.com/thanhtrungfruits-291804LXFW/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'hosting_details' => 'IP: 103.7.41.224',
                'domain_provider' => 'nasani.vn',
                'description' => 'Tên miền chính (SSL): thanhtrungfruits.com, tên phụ: tructhanhtrungfruits.com',
            ],
            [
                'name' => 'Nẵng Cầu Đức Hòa',
                'domain_name' => 'nangcauduchoa.com',
                'production_link' => 'https://nangcauduchoa.com/',
                'demo_link' => 'https://demo.webhieuqua.com/nangcauduchoa-482917ABKD/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'ssl_provider' => 'Có SSL trả phí',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => 'Suất Ăn Công Nghiệp Bàu Bàng',
                'domain_name' => 'suatancongnghiepbaubang.com',
                'production_link' => 'https://suatancongnghiepbaubang.com/',
                'demo_link' => 'https://demo.webhieuqua.com/suatancongnghiepbaubang-705163QZMT/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '3GB',
                'domain_provider' => 'nasani.vn',
            ],
            [
                'name' => '2TA',
                'domain_name' => '2ta.com.vn',
                'production_link' => 'https://2ta.com.vn/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 1100000,
                'status' => 'completed',
                'payment_status' => 'fully_paid',
                'hosting_package' => '1GB',
                'domain_provider' => 'pavietnam.vn',
            ],
            [
                'name' => 'Toàn Tâm Việt',
                'domain_name' => 'toantamviet.com',
                'design_link' => 'https://design.webhieuqua.com/toantamviet/',
                'demo_link' => 'https://demo.webhieuqua.com/tamtoanviet_kR8tP9vN2mXb/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 0,
                'status' => 'in_progress',
                'payment_status' => 'unpaid',
            ],
            [
                'name' => 'Ace Tax',
                'domain_name' => 'ace-tax.com',
                'design_link' => 'https://design.webhieuqua.com/ace-tax/',
                'demo_link' => 'https://demo.webhieuqua.com/ace-tax/',
                'features' => ['Cơ bản', 'Responsive', 'Mobile'],
                'project_price' => 1100000,
                'deposit_amount' => 0,
                'status' => 'in_progress',
                'payment_status' => 'unpaid',
            ],
        ];

        $count = 0;
        foreach ($projects as $data) {
            $data['client_id'] = $client->id;
            $data['project_type'] = $data['project_type'] ?? 'new';
            $data['remaining_amount'] = $data['project_price'] - $data['deposit_amount'];

            if ($data['payment_status'] === 'fully_paid') {
                $data['remaining_amount'] = 0;
                $data['payment_completion_date'] = now()->subMonths(rand(1, 6));
            }

            Project::create($data);
            $count++;
        }

        $this->command->info("Đã tạo khách hàng 'Anh Sinh' và {$count} dự án.");
    }
}
